accessibility fixes and new pa11y github test"

diff --git a/.github/workflows/pa11y.yml b/.github/workflows/pa11y.yml
--- a/.github/workflows/pa11y.yml
+++ b/.github/workflows/pa11y.yml
@@ -1,103 +1,75 @@
-name: Pa11y
+name: Pa11y Accessibility Checks
 
 on: [push, pull_request]
 
 jobs:
-  accessibility:
-    name: Test
+  mysql:
     runs-on: ubuntu-latest
 
+    # Define environment variables for MySQL and Rails
     env:
       DB_ADAPTER: mysql2
       MYSQL_PWD: root
       RAILS_ENV: test
 
     steps:
-      - uses: actions/checkout@v2
+    # Checkout the repo
+    - uses: actions/checkout@v2
+
+    # Install Ruby and run bundler
+    - uses: ruby/setup-ruby@v1
       with:
-        fetch-depth: 1
+        ruby-version: 2.6.3
+        bundler-cache: true
 
-      - name: 'Install  MySQL Packages'
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y mysql-client libmysqlclient-dev
+    # Install Node
+    - uses: actions/setup-node@v2
+      with:
+        cache: 'yarn'
 
-      - name: 'Determine Ruby and Bundler Versions from Gemfile.lock'
-        run: |
-          echo "RUBY_VERSION=`cat ./Gemfile.lock | grep -A 1 'RUBY VERSION' | grep 'ruby' | grep -oE '[0-9]\.[0-9]'`" >> $GITHUB_ENV
-          echo "BUNDLER_VERSION=`cat ./Gemfile.lock | grep -A 1 'BUNDLED WITH' | grep -oE '[0-9]\.[0-9]'`" >> $GITHUB_ENV
+    # Copy all of the example configs over
+    - name: 'Setup Default Configuration'
+      run: |
+        cp config/database.yml.sample config/database.yml
+        cp config/initializers/contact_us.rb.example config/initializers/contact_us.rb
+        cp config/initializers/wicked_pdf.rb.example config/initializers/wicked_pdf.rb
 
-      - name: 'Install Ruby'
-        uses: ruby/setup-ruby@v1.68.0
-        with:
-          ruby-version: ${{ env.RUBY_VERSION }}
+    # Stub out the Rails credentials file so that we can start the Rails app
+    - name: 'Setup Credentials'
+      run: EDITOR='echo "$(cat config/credentials.yml.example)" >' bundle exec rails credentials:edit
 
-      # Try to retrieve the gems from the cache
-      - name: 'Cache Gems'
-        uses: actions/cache@v2.1.5
-        with:
-          path: vendor/bundle
-          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
-          restore-keys: |
-            ${{ runner.os }}-gem-
+    # Set the path to the wkhtmltopdf executable
+    - name: 'Determine wkhtmltopdf location'
+      run: echo "WICKED_PDF_PATH=`bundle exec which wkhtmltopdf`" >> $GITHUB_ENV
 
-      - name: 'Bundle Install'
-        run: |
-          gem install bundler -v ${{ env.BUNDLER_VERSION }}
-          bundle config path vendor/bundle
-          bundle install --jobs 4 --retry 3 --without pgsql rollbar aws
+    # Run yarn install for JS dependencies
+    - name: 'Yarn Install'
+      run: yarn install
 
-      - name: 'Setup Credentials'
-        run: |
-          # generate a default credential file and key
-          EDITOR='echo "$(cat config/credentials.yml.example)" >' bundle exec rails credentials:edit
+    # Start the DB server and initialize the DB
+    - name: 'Start MySQL'
+      run: |
+        sudo systemctl start mysql
+        bin/rails db:setup RAILS_ENV=test
+        bin/rails db:migrate RAILS_ENV=test
 
-      # Try to retrieve the yarn JS dependencies from the cache
-      - name: 'Cache Yarn Packages'
-        uses: actions/cache@v1
-        with:
-          path: node_modules/
-          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
-          restore-keys: |
-            ${{ runner.os }}-build-${{ env.cache-name }}-
-            ${{ runner.os }}-build-
-            ${{ runner.os }}-yarn-
-            ${{ runner.os }}-
+    # Prebuild the CSS, JS and image assets
+    - name: 'Precompile all of the Assets'
+      run: bin/rails assets:precompile
 
-      - name: 'Determine wkhtmltopdf location'
-        run: echo "WICKED_PDF_PATH=`bundle exec which wkhtmltopdf`" >> $GITHUB_ENV
+    - name: Run pa11y-ci tests
+      run: yarn pa11y-sitemap
 
-      - name: 'Yarn Install'
-        run: |
-          yarn install
+    # - name: Read pa11y-ci test results
+    #   id: pa11yci_results
 
-      - name: 'Start MySQL'
-        run: sudo systemctl start mysql
+    #   uses: juliangruber/read-file-action@v1
+    #   with:
+    #     path: pa11yci/pa11yci-results.txt
 
-      - name: 'Setup Test DB'
-        run: bin/rails db:setup RAILS_ENV=test
-
-      - name: 'Migrate DB'
-        run: bin/rails db:migrate RAILS_ENV=test
-
-      - name: 'Compile Assets'
-        run: |
-          bin/rails webpacker:compile
-          bin/rails assets:precompile
-
-      - name: Run pa11y-ci tests
-        run: npm run test-a11y
-
-      - name: Read pa11y-ci test results
-        id: pa11yci_results
-
-        uses: juliangruber/read-file-action@v1
-        with:
-          path: pa11yci/pa11yci-results.txt
-
-      - name: Check for pa11y-ci errors
-        if: contains(steps.pa11yci_results.outputs.content, 'Errors in')
-        run: |
-          echo "::error::Accessibility errors were found."
-          echo "${{ steps.pa11yci_results.outputs.content }}"
-          exit 1
+    # - name: Check for pa11y-ci errors
+    #   if: contains(steps.pa11yci_results.outputs.content, 'Errors in')
+    #   run: |
+    #     echo "::error::Accessibility errors were found."
+    #     echo "${{ steps.pa11yci_results.outputs.content }}"
+    #     exit 1
